[theme]
primaryColor="#2870ed"
backgroundColor= "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#222529"
baseRadius="none"
buttonRadius="none"
font="sans-serif"

[browser]
gatherUsageStats = true